// 河南省明清衙署数据（基于测绘与文献）
const yamenData = [
    {
        name: "南阳府衙",
        level: "府衙",
        lat: 32.9940,
        lng: 112.5275,
        built: "元至元八年(1271)",
        eraGroup: "元代",
        hallSpec: "面阔5间 22.6m",
        roof: "硬山",
        area: 36000,
        status: "现存",
        desc: "保存最完整的府级官署，中轴线建筑完整。",
        source: "牛淑杰2003；实测"
    },
    {
        name: "内乡县衙",
        level: "县衙",
        lat: 33.0472,
        lng: 111.8433,
        built: "元大德八年(1304)",
        eraGroup: "元代",
        hallSpec: "面阔5间 16.8m",
        roof: "硬山",
        area: 47000,
        status: "现存",
        desc: "‘天下第一衙’，清代县级官署典范。",
        source: "内乡县衙博物馆"
    },
    {
        name: "叶县县衙",
        level: "县衙",
        lat: 33.6275,
        lng: 113.3542,
        built: "明洪武二年(1369)",
        eraGroup: "明代",
        hallSpec: "面阔5间 19.4m",
        roof: "硬山",
        area: 16848,
        status: "现存",
        desc: "明代县衙重要实例，中轴线完整。",
        source: "清华测绘十年"
    },
    {
        name: "密县县衙",
        level: "县衙",
        lat: 34.5342,
        lng: 113.3773,
        built: "隋大业始建，明清重建",
        eraGroup: "明清重建",
        hallSpec: "面阔5间 18m",
        roof: "硬山",
        area: 20000,
        status: "现存",
        desc: "历史最悠久的县衙之一。",
        source: "新密市志"
    },
    {
        name: "开封府衙",
        level: "府衙",
        lat: 34.7960,
        lng: 114.3485,
        built: "北宋始建，明清重建",
        eraGroup: "明清重建",
        hallSpec: "面阔5间(文献)",
        roof: "硬山/悬山",
        area: 40000,
        status: "遗址",
        desc: "北宋天下首府，现为考古遗址。",
        source: "开封府志"
    },
    {
        name: "洛阳府衙",
        level: "府衙",
        lat: 34.6214,
        lng: 112.4542,
        built: "明洪武年间",
        eraGroup: "明代",
        hallSpec: "面阔5间(推断)",
        roof: "硬山",
        area: 30000,
        status: "遗址",
        desc: "清代河南府治所，现存基址。",
        source: "河南府志"
    },
    {
        name: "淮阳府衙",
        level: "府衙",
        lat: 33.7362,
        lng: 114.8820,
        built: "清康熙年间",
        eraGroup: "清代",
        hallSpec: "面阔5间(文献)",
        roof: "硬山",
        area: 25000,
        status: "遗址",
        desc: "陈州府治所，部分基址留存。",
        source: "淮阳县志"
    }
];